modules/integration/tests-integration/tests-sample/src/test/java/org/wso2/carbon/esb/samples/test/miscellaneous/Sample100TestCase.java, modules/integration/tests-integration/tests-transport/src/test/java/org/wso2/carbon/esb/file/inbound/transport/test/FtpInboundTransportTest.java
Fixed errors in Sample100TestCase and FtpInboundTransportTest
=> Correcting errors in test cases

modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/local/carbon.xml, modules/integration/tests-integration/tests-transport/src/test/resources/testng.xml
revert changes done to carbon.xml , no longer needed
=> revert local carbon.xml and uncomment skipped tests from testng.xml

modules/integration/tests-integration/tests-transport/src/test/java/org/wso2/carbon/esb/nhttp/transport/test/ResponseAfterNttpEnabledTestCase.java
fix for error in deleting inbound endpoint in ResponseAfterNttpEnabledTestCase
=> fix cannot delete inbound error in ResponseAfterNttpEnabledTestCase

modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/synapseconfig/processor/forwarding/InMemoryStoreSynapse1.xml, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/synapseconfig/processor/forwarding/Retry_On_SOAPFault_In_Out.xml
Failed Integration tests for the message processor was fixed - ESB M7 release.
=> Message Processor failed test cases were fixed.

modules/integration/tests-integration/tests-transport/src/test/java/org/wso2/carbon/esb/jms/transport/test/ESBJAVA1832MessageInjectorTestCase.java, modules/integration/tests-integration/tests-transport/src/test/java/org/wso2/carbon/esb/jms/transport/test/JMSAccessSOAPFaultDataTestCase.java, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/jms/transport/JMSAXISFault.xml, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/jms/transport/msgInjection/msg_injecting_task.xml, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/jms/transport/msgInjection/msg_store.xml
=> JMS failed test cases were fixed.

modules/samples/product/src/main/conf/synapse/synapse_sample_300.xml
Added sample 300 synapse config fix -- Missing Task Manager Element
=> Fixing sample 300

modules/integration/tests-integration/tests-other/src/test/resources/artifacts/ESB/synapseconfig/customSSLprofileWithsecurevault/secret-conf.properties
keystore.identity.location path fixed
=> CustomSSLProfileWithSecureVault test case fix

modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/property/PropertyIntegrationXpathURLPropertyTestCase.java
updated with thread sleep to allow logs to be created
=> PropertyIntegrationXpathURLPropertyTestCase updated 

modules/integration/tests-integration/tests-patches/src/test/java/org/wso2/carbon/esb/car/deployment/test/ESBJAVA3611EndpointTestCase.java
sleep time increased to allow carbon app to be deployed
=> ESBJAVA3611EndpointTestCase fix

modules/integration/tests-integration/tests-transport/src/test/java/org/wso2/carbon/esb/jms/transport/test/JMSMessageStoreProcRESTTestCase.java
Use different SimpleHttpClient which sends json payload correctly
=> JMSMessageStoreProcRESTTestCase fix

modules/distribution/pom.xml, modules/features/pom.xml, modules/features/product/org.wso2.esb.samples.feature/pom.xml, modules/features/product/org.wso2.esb.styles.feature/pom.xml, modules/features/product/pom.xml, modules/integration/pom.xml, modules/integration/service-samples/pom.xml, modules/integration/test-common/admin-clients/pom.xml, modules/integration/test-common/extensions/pom.xml, modules/integration/test-common/integration-test-utils/pom.xml, modules/integration/test-common/pom.xml, modules/integration/test-common/ui-pages/pom.xml, modules/integration/tests-integration/reports/pom.xml, modules/integration/tests-integration/tests-mediator-1/pom.xml, modules/integration/tests-integration/tests-mediator-2/pom.xml, modules/integration/tests-integration/tests-other/pom.xml, modules/integration/tests-integration/tests-patches/pom.xml, modules/integration/tests-integration/tests-platform/pom.xml, modules/integration/tests-integration/tests-platform/tests-rabbitmq/pom.xml, modules/integration/tests-integration/tests-sample/pom.xml, modules/integration/tests-integration/tests-service/pom.xml, modules/integration/tests-integration/tests-transport/pom.xml, modules/integration/tests-ui-integration/tests-ui/pom.xml, modules/p2-profile/pom.xml, modules/samples/pom.xml, modules/samples/product/pom.xml, modules/styles/pom.xml, modules/styles/product/pom.xml, pom.xml
Version updated to 4.9.0-RC1-SNAPSHOT
=> Release 4.9.0 BETA

modules/integration/tests-integration/tests-transport/src/test/java/org/wso2/carbon/esb/vfs/transport/test/VFSTransportTestCase.java
Fix for integration test failure, Added line to create a folder to move the file if it doesn't exists.
=> vfs intergration test failure

modules/integration/tests-integration/tests-mediator-1/src/test/resources/testng.xml, modules/integration/tests-integration/tests-mediator-2/src/test/resources/testng.xml, modules/integration/tests-integration/tests-sample/src/test/resources/testng.xml, modules/integration/tests-integration/tests-service/src/test/resources/testng.xml, modules/integration/tests-integration/tests-transport/src/test/resources/testng.xml
Some of test cases disabled since those are failing in batch execution, but success in individual run
=> Some tests disabled 

modules/distribution/src/main/assembly/bin.xml, modules/p2-profile/pom.xml, pom.xml
Removed the bam service data agent from p2-profile since it is an optional feature
bin.xml file was changed to take the wso2carbon-version.txt from local repo since kernel has an issue with version number
=> Updated the carbon-identiy, carbon-commons version to the latest snapshot

modules/distribution/src/main/conf/nhttp.properties, modules/integration/tests-integration/tests-mediator-1/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-mediator-1/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-mediator-1/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-other/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-other/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-other/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-sample/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-sample/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-sample/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-service/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-service/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-service/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-transport/src/test/java/org/wso2/carbon/esb/jms/inbound/transport/test/JMSInboundMessagePollingTestCase.java, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-ui-integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-ui-integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-ui-integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties
Reverts wso2/product-esb#319 - to update versions to RC3-SNAPSHOT
=> Revert "http.socket.reuseaddr=true parameter added to configuration

modules/distribution/src/main/conf/nhttp.properties, modules/integration/tests-integration/tests-mediator-1/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-mediator-1/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-mediator-1/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-other/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-other/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-other/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-sample/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-sample/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-sample/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-service/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-service/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-service/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-integration/tests-transport/src/test/java/org/wso2/carbon/esb/jms/inbound/transport/test/JMSInboundMessagePollingTestCase.java, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-ui-integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-ui-integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-ui-integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties, modules/integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/nhttp.properties, modules/integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/MaxOpenConnections/passthru-http.properties, modules/integration/tests-ui/src/test/resources/artifacts/ESB/synapseconfig/nhttp_transport/nhttp.properties
added to nhttp.properties and passthru-http.properties files
=> http.socket.reuseaddr property added to property files

LICENSE.txt, modules/distribution/pom.xml, modules/distribution/src/main/assembly/bin.xml
1. By adding default directory permission and overriding it from bin.xml
(explicitly file permissions added, because some files are having incorrect permission inside the distribution)
2. updated the license.txt file
=> Corrected the directory permissions

modules/integration/test-common/integration-test-utils/src/main/java/org/wso2/esb/integration/common/utils/ESBIntegrationTest.java, modules/integration/test-common/integration-test-utils/src/main/java/org/wso2/esb/integration/common/utils/ESBTestCaseUtils.java, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/defaultconfigs/synapse.xml, modules/integration/tests-integration/tests-other/src/test/resources/artifacts/ESB/defaultconfigs/synapse.xml, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/defaultconfigs/synapse.xml, modules/integration/tests-integration/tests-platform/tests-rabbitmq/src/test/resources/artifacts/ESB/defaultconfigs/synapse.xml, modules/integration/tests-integration/tests-sample/src/test/resources/artifacts/ESB/defaultconfigs/synapse.xml, modules/integration/tests-integration/tests-service/src/test/resources/artifacts/ESB/defaultconfigs/synapse.xml, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/defaultconfigs/synapse.xml, modules/integration/tests-ui-integration/tests-ui/src/test/resources/artifacts/ESB/defaultconfigs/synapse.xml, modules/integration/tests-ui/src/test/resources/artifacts/ESB/defaultconfigs/synapse.xml, modules/samples/integration-scenarios/starbucks_sample/StarbucksServicePlatform/artifacts/ESB/defaultconfigs/synapse.xml, src/test/resources/artifacts/ESB/defaultconfigs/synapse.xml
This fix copy default synapse if synapse config is corrupted  during a test
=> Fix for build failures #648, #652 and #750 in Jenkins

modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/loggingProxy/PickEndPointFromRegistryTestCase.java, modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/loggingProxy/WSDLOptionsSpecifiedSourceUrlTestCase.java
In PickEndPointFromRegistryTestCase and WSDLOptionsSpecifiedSourceUrlTestCase classes
=> Additional logs added to find the intermittent build failures 

modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/loggingProxy/PickEndPointFromRegistryTestCase.java, modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/loggingProxy/ProxyServiceEnablingHTTPSTestCase.java, modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/loggingProxy/ProxyServiceEnablingHTTPTestCase.java, modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/loggingProxy/RequestLogLevelFullResponseLogLevelFullTestCase.java, modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/loggingProxy/RequestLogLevelNoneResponseLogLevelNoneTestCase.java, modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/loggingProxy/RequestLogLevelSimpleResponseLogLevelSimpleTestCase.java, modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/loggingProxy/WSDLOptionsPickedFromRegistryTestCase.java, modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/loggingProxy/WSDLOptionsSpecifiedInlineTestCase.java, modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/loggingProxy/WSDLOptionsSpecifiedSourceUrlTestCase.java, modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/scheduledtask/test/InjectToSequenceTestCase.java
=> Disabled test methods which do not have any implementation 

modules/integration/tests-integration/tests-patches/src/test/java/org/wso2/carbon/esb/endpoint/test/ESBJAVA4231EmptyPayloadInFailoverLoadBalanceEndpoint.java, modules/integration/tests-integration/tests-patches/src/test/resources/testng.xml
Adding Integration Test for ESBJAVA-4231 to testng
=> Adding test to testng

modules/integration/test-common/integration-test-utils/src/main/java/org/wso2/esb/integration/common/utils/ESBTestCaseUtils.java, modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/callOut/DynamicEndpointTestCase.java, modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/callOut/TransportHeaderTestCase.java, modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/callOut/ValidPathAxis2RepoTestCase.java, modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/callOut/ValidPathAxis2XmlTestCase.java, modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/callTemplate/CallTemplateIntegrationParamsWithValuesTestCase.java, modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/classMediator/ClassMediationWithLoadOfPropertiesTestCase.java, modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/classMediator/InvokeAfterRemovingPropertiesTestCase.java, modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/classMediator/PropertyPersistenceAddingTestCase.java, modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/classMediator/PropertyPersistenceDeletingAndAddingTstCase.java, modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/classMediator/PropertyPersistenceDeletingTestCase.java
Mediator-1 module test cases reviewed and corrected.
=> EsbUtils.updateESBConfiguration refactored to validate artifacts

modules/integration/tests-integration/tests-mediator-2/src/test/java/org/wso2/carbon/esb/mediator/test/script/GroovyScriptSupportTestCase.java, modules/integration/tests-integration/tests-mediator-2/src/test/java/org/wso2/carbon/esb/mediator/test/script/GroovySetPayloadJSONTestCase.java, modules/integration/tests-integration/tests-mediator-2/src/test/java/org/wso2/carbon/esb/mediator/test/smooks/SmooksIntegrationTestCase.java, modules/integration/tests-integration/tests-mediator-2/src/test/java/org/wso2/carbon/esb/mediator/test/smooks/SmooksMediatorConfigFromConfigRegistryTestCase.java, modules/integration/tests-integration/tests-mediator-2/src/test/java/org/wso2/carbon/esb/mediator/test/smooks/SmooksMediatorConfigFromLocalEntryTestCase.java, modules/integration/tests-integration/tests-mediator-2/src/test/java/org/wso2/carbon/esb/mediator/test/spring/ProvidingDifferentBeanNamesTestCase.java, modules/integration/tests-integration/tests-mediator-2/src/test/java/org/wso2/carbon/esb/message/processor/test/MessageProcessorPersistenceTestCase.java, modules/integration/tests-integration/tests-service/src/test/java/org/wso2/carbon/esb/endpoint/test/FailOverWithDisabledErrors.java
Thread sleep changes reverted from https://github.com/wso2/product-esb/pull/379
=> Test case updates in mediator-2 and service modules

modules/distribution/pom.xml, modules/distribution/src/main/assembly/bin.xml, modules/p2-profile/pom.xml, pom.xml
=> carbon-commons, deployment, multitenancy and identity versions updated

modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/clone/CloneFunctionalContextTestCase.java
Removed unwanted log level changing configurations
=> CloneFunctionalContextTestCase updated. 

modules/integration/tests-integration/tests-mediator-1/src/test/resources/artifacts/ESB/synapseconfig/config17/synapse.xml
Removing the outer iterate mediator
=> Refine the AggregateWithHighMaxAndLowMinTestCase

modules/integration/tests-integration/tests-mediator-1/src/test/java/org/wso2/carbon/esb/mediator/test/rule/MultipleRuleSetPropertyTestCase.java, modules/integration/tests-integration/tests-mediator-1/src/test/resources/artifacts/ESB/synapseconfig/config_multiple_rule/synapse.xml
Changed the test case's assert check for axis fault to check for the proxy response with WRONG_RULE
=> Changing the wrong rule ep to proxy service

modules/p2-profile/pom.xml
* Adding new DAS publisher as a feature
* Remove existing message flow tracer feature
=> DAS Publisher feature added

modules/distribution/src/main/conf/synapse.properties, modules/p2-profile/pom.xml
Correlations with:
https://github.com/wso2/wso2-synapse/pull/458
https://github.com/wso2/carbon-mediation/pull/528
* Remove carbon console new statistics feature
* Add new parameters to collect payloads & properties
=> Modify new statistic analytics

modules/distribution/src/main/conf/synapse.properties
Refer:
https://github.com/wso2/wso2-synapse/pull/461
https://github.com/wso2/carbon-mediation/pull/529
Changed synapse property
=> Modify stats collector for tracing - 2

modules/integration/tests-integration/tests-mediator-2/src/test/java/org/wso2/carbon/esb/mediator/test/tracer/TracerTestCase.java, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/synapseconfig/tracer/synapse.properties, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/synapseconfig/tracer/tracer.xml
Adding new synapse.properties
Enable statistics in proxy config
=> Fix for tracing test-case

modules/integration/tests-integration/tests-patches/src/test/java/org/wso2/carbon/esb/passthru/transport/test/ESBJAVA4423CustomStatusDescriptionTest.java, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/passthru/transport/httpproxy/httpCustomProxy.xml, modules/integration/tests-integration/tests-patches/src/test/resources/testng.xml
This PR depends on https://github.com/wso2/wso2-synapse/pull/466. Apply it first.
=> fixing ESBJAVA4423

modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/synapseconfig/tracer/tracer.xml
Added statistics="enable" property to sequence
=> Adding statistics enabling to testSequence to fix testcase

modules/integration/tests-integration/tests-patches/src/test/java/org/wso2/carbon/esb/passthru/transport/test/ESBJAVA4394.java, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/passthru/transport/ESBJAVA4394-config.xml, modules/integration/tests-integration/tests-patches/src/test/resources/testng.xml
Please make sure to merge the pull request https://github.com/wso2/wso2-synapse/pull/445, before merging this
=> test for ESBJAVA-4394

modules/integration/tests-integration/tests-transport/src/test/java/org/wso2/carbon/esb/mailto/transport/sender/test/SendMailWithSecondaryAccountThroughESBTestCase.java, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/mailTransport/mailTransportSender/secondaryAccount/axis2.xml, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/mailTransport/mailTransportSender/secondaryAccount/mail_sender_secondary.xml
Improvement in PR : https://github.com/wso2/wso2-axis2-transports/pull/72
=> Adding testcase SendMailWithSecondaryAccountThroughESBTestCase

modules/integration/tests-integration/tests-patches/src/test/java/org/wso2/carbon/esb/passthru/transport/test/ESBJAVA4328RestUrlPostFixValueEncodeTestCase.java, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/mediatorconfig/property/REST_URL_postfix_encode.xml, modules/integration/tests-integration/tests-patches/src/test/resources/testng.xml
Test case for the improvement: https://github.com/wso2/wso2-synapse/pull/541
=> Adding test case for REST_URL_POSTFIX improvement

modules/distribution/src/main/assembly/bin.xml, modules/integration/test-common/integration-test-utils/pom.xml, modules/integration/test-common/pom.xml, pom.xml
Fixing the https://wso2.org/jira/browse/ESBJAVA-4060 issue with httpclient version upgrade
=> Adding the httpclient 4.3.2 version

modules/integration/tests-integration/tests-mediator-1/.gitignore, modules/integration/tests-integration/tests-mediator-2/.gitignore, modules/integration/tests-integration/tests-other/.gitignore, modules/integration/tests-integration/tests-patches/.gitignore, modules/integration/tests-integration/tests-platform/tests-rabbitmq/.gitignore, modules/integration/tests-integration/tests-sample/.gitignore, modules/integration/tests-integration/tests-service/.gitignore, modules/integration/tests-integration/tests-transport/.gitignore, modules/integration/tests-ui-integration/tests-ui/.gitignore
This will help to ignore files created when building the repository
=> Adding gitignore

modules/distribution/src/main/assembly/bin.xml, modules/p2-profile/pom.xml, pom.xml
Relates to : https://github.com/wso2/carbon-mediation/pull/620
=> Adding event-publisher-aggregate feature

modules/p2-profile/pom.xml
Removing previous statistics collection from synapse
Synapse PR: https://github.com/wso2/wso2-synapse/pull/569
Carbon-Mediation: https://github.com/wso2/carbon-mediation/pull/623
=> Purge old statistics implementation

modules/integration/tests-integration/tests-mediator-1/src/test/resources/artifacts/ESB/samples/synapse_sample_62.xml, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/samples/synapse_sample_62.xml, modules/integration/tests-integration/tests-other/src/test/resources/artifacts/ESB/samples/synapse_sample_62.xml, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/samples/synapse_sample_62.xml, modules/integration/tests-integration/tests-sample/src/test/resources/artifacts/ESB/samples/synapse_sample_62.xml, modules/integration/tests-integration/tests-service/src/test/resources/artifacts/ESB/samples/synapse_sample_62.xml, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/samples/synapse_sample_62.xml, modules/integration/tests-ui-integration/tests-ui/src/test/resources/artifacts/ESB/samples/synapse_sample_62.xml, modules/samples/product/src/main/conf/synapse/synapse_sample_62.xml
Aggregate mediator
```
-                            expression="//m0:getSimpleQuoteResponse">
+                            expression="//m0:getQuoteResponse">
```
=> Change sample 62 config

modules/integration/tests-integration/tests-mediator-2/src/test/java/org/wso2/carbon/esb/mediator/test/xslt/XSLTonEmptySoapBodyWithSourceXPath.java, modules/integration/tests-integration/tests-mediator-2/src/test/resources/artifacts/ESB/mediatorconfig/xslt/xslt_empty_soap_body.xml
related PR https://github.com/wso2/wso2-synapse/pull/566
=> adding test for esbjava-3843

modules/distribution/src/main/assembly/bin.xml, modules/integration/tests-integration/tests-sample/src/test/java/org/wso2/carbon/esb/samples/test/endpoint/Sample62TestCase.java
* TMP - excluding bundles added via data-publisher feature
* make sample-62 test comply with , test framework's response
=> Fix build failures

modules/p2-profile/pom.xml
Fixing https://wso2.org/jira/browse/ESBJAVA-4762
=> Adding the sap transport jar to the product distribution

modules/distribution/src/main/conf/axis2.xml, modules/distribution/src/main/conf/axis2_nhttp.xml, modules/distribution/src/main/conf/axis2_pt.xml, modules/p2-profile/pom.xml
=> Revert "disabling tryIt feature"

modules/integration/tests-integration/tests-patches/src/test/java/org/wso2/carbon/esb/mediators/clone/ESBJAVA4913HandleExceptionTest.java, modules/integration/tests-integration/tests-patches/src/test/java/org/wso2/carbon/esb/passthru/transport/test/ESBJAVA4760ContentLengthHeaderTest.java, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/mediatorconfig/clone/cloneMediatorHandleException.xml, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/passthru/transport/ESBJAVA4760/ESBJAVA4760.xml, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/synapseconfig/rest/query_params_api.xml, modules/integration/tests-integration/tests-patches/src/test/resources/testng.xml
Test case to verify error sequence in clone mediator
jira : https://wso2.org/jira/browse/ESBJAVA-4913
=> [ESBJAVA-4913] Test case to verify error sequence in clone mediator.

modules/integration/tests-integration/tests-transport/src/test/java/org/wso2/carbon/esb/passthru/transport/test/ESBJAVA1994SOAPFormatSwitchingTestcase.java, modules/integration/tests-integration/tests-transport/src/test/resources/artifacts/ESB/passthru/transport/httpproxy/httpProxySwitchingSoap12.xml
Jira : https://wso2.org/jira/browse/ESBJAVA-1994
=> [ESBJAVA-1994] Adding test case for SOAP format conversion. 

modules/integration/tests-integration/tests-patches/src/test/java/org/wso2/carbon/esb/nhttp/transport/json/test/ESBJAVA4940CharacterEncodingRemovalTestCase.java, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/nhttp/transport/ESBJAVA4940/axis2.xml, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/nhttp/transport/ESBJAVA4940/synapseConfig.xml, modules/integration/tests-integration/tests-patches/src/test/resources/testng.xml
https://wso2.org/jira/browse/ESBJAVA-4940
=> Adding testcase for ESBJAVA-4940

modules/samples/product/src/main/conf/synapse/synapse_sample_800.xml
=> Revert "adding messageType to sample 800 configuration" since fix is provided with https://github.com/wso2/wso2-synapse/pull/681

modules/integration/tests-integration/tests-patches/src/test/java/org/wso2/carbon/esb/mediators/callout/ESBJAVA_3587_DisableChunkingTest.java, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/mediatorconfig/callout/disableChunkingProxy.xml, modules/integration/tests-integration/tests-patches/src/test/resources/artifacts/ESB/mediatorconfig/callout/log4j.properties, modules/integration/tests-integration/tests-patches/src/test/resources/testng.xml
Jira - https://wso2.org/jira/browse/ESBJAVA-3587
=> [ESBJAVA-3587]Added test case for DISABLE chunking for callout
